PoliTest4/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^ptest/', include('ptest.urls', namespace='ptest')),
    url(r'^', include('person.urls', namespace='person')),
]

person/urls.py
from django.conf.urls import url
from person import views

urlpatterns = [
    url(r'^$',views.index, name='home'),
    url(r'^id(?P<profile_id>\d+)/$', views.details, name='details'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^id(?P<profile_id>\d+)/edit/$', views.edit, name='edit'),
]

ptest/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from ptest import views
from ptest.views import QuestionDetailView, QuestionListView, QuestionVoteView, ResultsView

app_name = 'ptest'

urlpatterns = [
    url(r'^$', QuestionListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', QuestionDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/vote/$', login_required(QuestionVoteView.as_view()), name='vote'),
    url(r'^result/$', ResultsView.as_view(), name='result'),
]

person/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=150, blank=True,)
    birth_date = models.DateField(blank=True,)
    sex = models.CharField(max_length=10, blank=True, )
    region = models.CharField(max_length=50, blank=True,)
    ideology = models.CharField(max_length=150, blank=True, )
    religion = models.CharField(max_length=150, blank=True, )
    avatar = models.ImageField(blank=True, upload_to='static/uploads')
    about = models.TextField(blank=True)

    def __str__(self):
        return self.name


class WallPost(models.Model):
    receiver = models.ForeignKey(UserProfile)
    sender = models.ForeignKey(UserProfile, related_name="sender")

    pub_date = models.DateTimeField()
    body = models.TextField()

    def __str__(self):
        return self.body[:20]

ptest/models.py
from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible



class Question(models.Model):
    question = models.TextField()
    description = models.CharField(max_length=500, blank=True)

    def count_choices(self):
        return self.choice_set.count()

    def count_total_votes(self):
        result = 0
        for choice in self.choice_set.all():
            result += choice.count_votes()
        return result

    def can_vote(self, user):
        return not self.vote_set.filter(user=user).exists()

    def __str__(self):
        return self.question


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice = models.CharField(max_length=500)

    def count_votes(self):
        return self.vote_set.count()

    def __unicode__(self):
        return self.choice

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.choice


class Vote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    question = models.ForeignKey(Question)
    choice = models.ForeignKey(Choice)

    def __unicode__(self):
        return u'Vote for %s' % (self.choice)

    class Meta:
        unique_together = (('user', 'question'))

    def __str__(self):
        return str(self.user.id)+'-' + str(self.question.id)+'-' + self.choice.choice

person/forms.py
from django import forms
from django.contrib.auth.models import User
from person.models import UserProfile, WallPost


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)


class WallPostForm(forms.ModelForm):
    class Meta:
        model = WallPost
        fields=('body', )

person/views.py
from django.shortcuts import render, redirect
from person.models import UserProfile, WallPost
from person.forms import UserForm, UserProfileForm, WallPostForm
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.cache import cache_control
from django.utils import timezone

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    profiles = UserProfile.objects.all()
    return render(request, 'index.html', {'profiles':profiles})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def details(request, profile_id):
    profile = UserProfile.objects.get(id=profile_id)
    wall_posts = profile.wallpost_set.order_by('-pub_date')
    form = WallPostForm()
    if request.POST:
        form = WallPostForm(request.POST)
        if form.is_valid():
            wall_post = form.save(commit=False)
            wall_post.receiver = profile
            wall_post.sender = request.user.userprofile
            wall_post.pub_date = timezone.now()
            wall_post.save()
            return redirect('person:details', profile_id)
    return render(request, 'details.html',{'profile':profile,
                                           'wall_posts':wall_posts,
                                           'form':form})


def register(request):
    if request.POST:
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid():
            print('forms are valid')
        else:
            print('forms ar invalid')

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if profile.avatar:
                profile.avatar = request.FILES['avatar']
            profile.save()
        else:
            print(user_form.errors, profile_form.errors)
        return redirect('person:home')
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        return render (request, "register.html", {'user_form': user_form,
                                                  'profile_form': profile_form})

def user_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('person:details', profile_id = user.userprofile.id)
        else:
            return redirect('person:register')
    else:
        return render(request, 'login.html', {})


def user_logout(request):
    logout(request)
    return redirect('person:home')


def edit(request, profile_id):
    profile = UserProfile.objects.get(id=profile_id)
    profile_form = UserProfileForm(instance=profile)
    if not request.user.is_authenticated():
        profile_form = UserProfileForm(instance=profile)
        return redirect("person:login")
   # elif int(profile_id) != request.user.id:
   #     return redirect("person:edit", request.user.id)
    else:
        if request.POST:
            profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
            if profile_form.is_valid():
                profile_form.save()
                return redirect("person:details", profile.id)
        return render(request, "edit.html", {'profile':profile,
                                             'profile_form':profile_form})

ptest/views.py
from django.views.generic import DetailView, ListView, RedirectView, TemplateView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render, redirect

from ptest.models import Choice, Question, Vote


class QuestionListView(ListView):
    model = Question


class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        context['question'].votable = self.object.can_vote(self.request.user)
        return context


class QuestionVoteView(RedirectView):
    def post(self, request, *args, **kwargs):
        question = Question.objects.get(id=kwargs['pk'])
        user = request.user
        choice = Choice.objects.get(id=request.POST['choice_pk'])
        Vote.objects.create(question=question, user=user, choice=choice)
        return super(QuestionVoteView, self).post(request, *args, **kwargs)

    def get_redirect_url(self, **kwargs):
        return reverse_lazy('ptest:detail', args=[kwargs['pk']])


class ResultsView(ListView):
    model = Vote

person/templates/details.html
{% extends 'person/base.html' %}

{% block title %}
    {{ profile.name }}
{% endblock %}

{% block body %}
    <h2> {{ profile.name }}</h2><a href="{% url 'person:edit' profile.id %}">&nbsp;&nbsp;&nbsp; Edit</a><br><br>
    <a href="{% url 'ptest:result' %}">&nbsp;&nbsp;&nbsp;  Test Results</a><br><br>

    {% if profile.avatar %}
        <img src="/{{ profile.avatar }}" alt=""  height="200" width="200" ><br>
    {% else %}
        <p>No image</p><br>
    {% endif %}
    {% if  profile.birth_date  %}
    <i> &nbsp;&nbsp;{{ profile.birth_date }}</i> <br>
    {% endif %}
  {% if  profile.sex  %}
    <i> &nbsp;&nbsp;{{ profile.sex}}</i> <br>
    {% endif %}
  {% if  profile.region  %}
    <i> &nbsp;&nbsp;{{ profile.region }}</i> <br>
    {% endif %}
  {% if  profile.ideology  %}
    <i> &nbsp;&nbsp;{{ profile.ideology }}</i> <br>
    {% endif %}
  {% if  profile.religion  %}
    <i> &nbsp;&nbsp;{{ profile.religion }}</i> <br>
    {% endif %}
  {% if  profile.about  %}
    <i> &nbsp;&nbsp;{{ profile.about }} </i><br>
    {% endif %}


{% endblock %}

person/templates/edit.html
{% extends "person/base.html" %}
{% block title %} Edit {{ profile.name }}{% endblock %}

{% block body %}
   <form action="{% url 'person:edit' profile.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ profile_form.as_p }}
        <input type = "submit" value="Save Changes">
    </form>
{% endblock %}

person/templates/index.html
{% extends 'person/base.html' %}

{% block title %} Home {% endblock %}
{% block body %}
<br>
    <h1>   Welcome!</h1><br>
      <ul>

        {% for profile in profiles %}

            <li><a href="{% url 'person:details' profile.id %}"><span class="glyphicon glyphicon-expand aria-hidden=true"></span>&nbsp;{{ profile.name }}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

person/templates/login.html
{% extends "person/base.html" %}
{% block title %} Login {% endblock %}

{%  block body %}

      <ul>

        {% for profile in profiles %}
           <h1>   Welcome!</h1>
            <li><a href="{% url 'person:details' profile.id %}">{{ profile.name }}</a> </li>
        {% endfor %}
    </ul>

    <h1>Login:</h1>
    <form action="{% url 'person:login' %}" method="post">
        {% csrf_token %}
        Username: <input type="text" name='username'><br>
        Password: <input type="password" name="password"><br>
        <input type="submit" value="Login">
    </form>

{% endblock %}

person/templates/person/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}User{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'images/girchi2.jpg' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block home %}{% endblock %}"><a href="{% url 'person:home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home&nbsp;&nbsp;</a>
                </li>

            <li class="{% block test %}{% endblock %}"><a href="{% url 'ptest:list' %}"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Test&nbsp;&nbsp;</a>

             {% if user.is_authenticated %}

                <li><a href="{% url 'person:logout' %}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout</a></li>
             {% else %}
                <li><a href="{% url 'person:register' %}"><span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register</a></li>
                <li><a href="{% url 'person:login' %}"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login</a></li>
             {% endif %}

            </ul>




         <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'person:home' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
        </div>

    </div>
</nav>

<h4>
{% if user.is_authenticated %} You are logged as {{ user.username }}{% else %}You are not logged in{% endif %}<br><br>
</h4>

{% block body %}
{% endblock %}
</body>
</html>

person/templates/register.html
{% extends "person/base.html" %}
{% block title %} Register {% endblock %}

{% block body %}
    <form action="{% url 'person:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type = "submit" value="Register">
    </form>


{% endblock %}